(ns semicon_robotics.actor
  "semicon_robotics clean-room actor — Clojure over the kotoba Datom log (EAVT, Datomic-isomorphic,
  ADR-2605262130 + ADR-2605312345). Fab-automation robotics — wafer handling design + implementation.

  Generated by 70-tools/scaffold_wave11_clj_datomic.py — replaces the Python main.py.
  CRUD + validation over a DI `DatomPort` seam (no external managed DB; the production
  adapter is kotoba-kqe, the test/browser adapter is `in-memory-datom`). No proprietary code."
  (:require [clojure.string :as str]))

;; ── Datomic-style schema (install via -transact) ──────────────────────────
(def schema
  "Attribute installs for this actor's entities (Datomic schema shape)."
  [;; WaferRobot
   {:db/ident :semicon_robotics.WaferRobot/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :semicon_robotics.WaferRobot/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :semicon_robotics.WaferRobot/vendor :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :semicon_robotics.WaferRobot/axes :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :semicon_robotics.WaferRobot/payloadKg :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :semicon_robotics.WaferRobot/cleanClass :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :semicon_robotics.WaferRobot/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :semicon_robotics.WaferRobot/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; EfemModule
   {:db/ident :semicon_robotics.EfemModule/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :semicon_robotics.EfemModule/robotId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :semicon_robotics.EfemModule/ports :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :semicon_robotics.EfemModule/ffuFlowM3h :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :semicon_robotics.EfemModule/status :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :semicon_robotics.EfemModule/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :semicon_robotics.EfemModule/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; TransferJob
   {:db/ident :semicon_robotics.TransferJob/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :semicon_robotics.TransferJob/robotId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :semicon_robotics.TransferJob/source :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :semicon_robotics.TransferJob/destination :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :semicon_robotics.TransferJob/status :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :semicon_robotics.TransferJob/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :semicon_robotics.TransferJob/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; LoadPort
   {:db/ident :semicon_robotics.LoadPort/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :semicon_robotics.LoadPort/moduleId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :semicon_robotics.LoadPort/standard :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :semicon_robotics.LoadPort/slots :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :semicon_robotics.LoadPort/occupied :db/valueType :db.type/boolean :db/cardinality :db.cardinality/one}
   {:db/ident :semicon_robotics.LoadPort/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :semicon_robotics.LoadPort/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; MotionProgram
   {:db/ident :semicon_robotics.MotionProgram/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :semicon_robotics.MotionProgram/robotId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :semicon_robotics.MotionProgram/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :semicon_robotics.MotionProgram/waypoints :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :semicon_robotics.MotionProgram/cycleTimeS :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :semicon_robotics.MotionProgram/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :semicon_robotics.MotionProgram/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Interlock
   {:db/ident :semicon_robotics.Interlock/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :semicon_robotics.Interlock/robotId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :semicon_robotics.Interlock/kind :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :semicon_robotics.Interlock/triggered :db/valueType :db.type/boolean :db/cardinality :db.cardinality/one}
   {:db/ident :semicon_robotics.Interlock/severity :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :semicon_robotics.Interlock/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :semicon_robotics.Interlock/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}])

(def entities #{"WaferRobot" "EfemModule" "TransferJob" "LoadPort" "MotionProgram" "Interlock"})

;; ── DatomPort — the DI seam to the kotoba Datom log ───────────────────────
(defprotocol DatomPort
  (-transact [this tx-data]
    "Append Datomic-shaped tx-data: entity maps {:db/id … attr v}, [:db/add e a v],
     [:db/retract e a v], [:db/retractEntity e].")
  (-pull [this eid]
    "Return the entity map for eid (incl. :db/id), or nil.")
  (-find-by-attr [this attr]
    "AEVT scan: the eids of every entity carrying attr."))

;; loud-failing default — a forgotten injection must never silently no-op
(defn unwired-datom []
  (reify DatomPort
    (-transact [_ _] (throw (ex-info "semicon_robotics: DatomPort not wired — inject kotoba-kqe or in-memory-datom" {:unwired true})))
    (-pull [_ _] (throw (ex-info "semicon_robotics: DatomPort not wired" {:unwired true})))
    (-find-by-attr [_ _] (throw (ex-info "semicon_robotics: DatomPort not wired" {:unwired true})))))

;; in-memory fake — interprets the Datomic tx-data subset over {eid {attr v}}
(defn in-memory-datom []
  (let [store (atom {})]
    (reify DatomPort
      (-transact [_ tx-data]
        (doseq [op tx-data]
          (cond
            (map? op) (swap! store update (:db/id op) merge (dissoc op :db/id))
            (and (vector? op) (= :db/add (first op)))
            (let [[_ e a v] op] (swap! store assoc-in [e a] v))
            (and (vector? op) (= :db/retract (first op)))
            (let [[_ e a] op] (swap! store update e dissoc a))
            (and (vector? op) (= :db/retractEntity (first op)))
            (let [[_ e] op] (swap! store dissoc e))))
        {:db-after @store})
      (-pull [_ eid] (when-let [m (get @store eid)] (assoc m :db/id eid)))
      (-find-by-attr [_ attr] (vec (for [[eid m] @store :when (contains? m attr)] eid))))))

;; ── coercion (portable) ───────────────────────────────────────────────────
(defn- as-long [v]
  (cond (number? v) #?(:clj (long v) :cljs v)
        (string? v) (try #?(:clj (Long/parseLong (str/trim v))
                            :cljs (let [n (js/parseInt v 10)] (if (js/isNaN n) 0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0))
        :else 0))

(defn- as-double [v]
  (cond (number? v) #?(:clj (double v) :cljs v)
        (string? v) (try #?(:clj (Double/parseDouble (str/trim v))
                            :cljs (let [n (js/parseFloat v)] (if (js/isNaN n) 0.0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0.0))
        :else 0.0))

(defn- as-bool [v]
  (boolean (#{"1" "true" "yes" "on" true} (if (string? v) (str/lower-case v) v))))

(defn- now []
  #?(:clj (str (java.time.Instant/now)) :cljs (.toISOString (js/Date.))))

(defn- new-id [prefix]
  (str prefix "_" (subs (str/replace (str (random-uuid)) "-" "") 0 16)))

(defn- require-fields [data fields]
  (let [missing (remove (fn [k] (some? (get data (keyword k)))) fields)]
    (when (seq missing)
      (throw (ex-info (str "Missing required fields: " (str/join ", " missing))
                      {:type :invalid-request :missing (vec missing)})))))

;; ── list surface: filtering + cursor pagination (L4 parity) ───────────────
(def ^:const default-limit 20)
(def ^:const max-limit 100)

(defn- index-of [v x]
  (loop [i 0] (cond (>= i (count v)) -1 (= (nth v i) x) i :else (recur (inc i)))))

(defn- apply-filters
  "Keep rows matching every {attr v} in flt (string-compared), attr restricted to allowed."
  [rows flt allowed]
  (let [allowed (set allowed)]
    (reduce (fn [rs [a v]]
              (if (and (contains? allowed a) (some? v))
                (filterv (fn [r] (= (str (get r a)) (str v))) rs)
                rs))
            (vec rows) (or flt {}))))

(defn- paginate
  "Cursor pagination over rows → {:object :data :has-more :count :total}.
   opts {:limit N :starting-after <db/id>}."
  [rows opts]
  (let [limit (min (max (or (:limit opts) default-limit) 1) max-limit)
        start (:starting-after opts)
        rows  (vec rows)
        rows  (if start
                (let [idx (index-of (mapv :db/id rows) start)]
                  (if (neg? idx) rows (subvec rows (inc idx))))
                rows)
        page  (vec (take limit rows))]
    {:object "list" :data page :has-more (> (count rows) limit)
     :count (count page) :total (count rows)}))

;; ── WaferRobot ────────────────────────────────────────────────────────────────
(defn create-wafer-robot
  "Create a WaferRobot."
  [port data]
  (require-fields data ["name" "vendor"])
  (let [id (new-id "sbot_waf")
        e {:db/id id
           :semicon_robotics.WaferRobot/id id
           :semicon_robotics.WaferRobot/name (get data :name)
           :semicon_robotics.WaferRobot/vendor (get data :vendor)
           :semicon_robotics.WaferRobot/axes (as-long (get data :axes))
           :semicon_robotics.WaferRobot/payloadKg (as-double (get data :payloadKg))
           :semicon_robotics.WaferRobot/cleanClass (get data :cleanClass)
           :semicon_robotics.WaferRobot/createdAt (now)
           :semicon_robotics.WaferRobot/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-wafer-robots
  "List WaferRobot with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-wafer-robots port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :semicon_robotics.WaferRobot/id))
         rows (apply-filters rows (:filter opts) [:semicon_robotics.WaferRobot/name :semicon_robotics.WaferRobot/vendor :semicon_robotics.WaferRobot/axes :semicon_robotics.WaferRobot/payloadKg :semicon_robotics.WaferRobot/cleanClass])]
     (paginate rows opts))))

(defn get-wafer-robot
  "Retrieve a WaferRobot by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-wafer-robot port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-wafer-robot
  "Update a WaferRobot; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :name) (conj [:db/add id :semicon_robotics.WaferRobot/name (get data :name)]))
                   (cond-> (contains? data :vendor) (conj [:db/add id :semicon_robotics.WaferRobot/vendor (get data :vendor)]))
                   (cond-> (contains? data :axes) (conj [:db/add id :semicon_robotics.WaferRobot/axes (as-long (get data :axes))]))
                   (cond-> (contains? data :payloadKg) (conj [:db/add id :semicon_robotics.WaferRobot/payloadKg (as-double (get data :payloadKg))]))
                   (cond-> (contains? data :cleanClass) (conj [:db/add id :semicon_robotics.WaferRobot/cleanClass (get data :cleanClass)]))
                   (conj [:db/add id :semicon_robotics.WaferRobot/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-wafer-robot
  "Delete a WaferRobot."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── EfemModule ────────────────────────────────────────────────────────────────
(defn create-efem-module
  "Create a EfemModule."
  [port data]
  (require-fields data ["ports" "ffuFlowM3h"])
  (let [id (new-id "sbot_efe")
        e {:db/id id
           :semicon_robotics.EfemModule/id id
           :semicon_robotics.EfemModule/robotId (get data :robotId)
           :semicon_robotics.EfemModule/ports (as-long (get data :ports))
           :semicon_robotics.EfemModule/ffuFlowM3h (as-double (get data :ffuFlowM3h))
           :semicon_robotics.EfemModule/status (get data :status)
           :semicon_robotics.EfemModule/createdAt (now)
           :semicon_robotics.EfemModule/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-efem-modules
  "List EfemModule with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-efem-modules port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :semicon_robotics.EfemModule/id))
         rows (apply-filters rows (:filter opts) [:semicon_robotics.EfemModule/robotId :semicon_robotics.EfemModule/ports :semicon_robotics.EfemModule/ffuFlowM3h :semicon_robotics.EfemModule/status])]
     (paginate rows opts))))

(defn get-efem-module
  "Retrieve a EfemModule by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-efem-module port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-efem-module
  "Update a EfemModule; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :robotId) (conj [:db/add id :semicon_robotics.EfemModule/robotId (get data :robotId)]))
                   (cond-> (contains? data :ports) (conj [:db/add id :semicon_robotics.EfemModule/ports (as-long (get data :ports))]))
                   (cond-> (contains? data :ffuFlowM3h) (conj [:db/add id :semicon_robotics.EfemModule/ffuFlowM3h (as-double (get data :ffuFlowM3h))]))
                   (cond-> (contains? data :status) (conj [:db/add id :semicon_robotics.EfemModule/status (get data :status)]))
                   (conj [:db/add id :semicon_robotics.EfemModule/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-efem-module
  "Delete a EfemModule."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── TransferJob ────────────────────────────────────────────────────────────────
(defn create-transfer-job
  "Create a TransferJob."
  [port data]
  (require-fields data ["source" "destination"])
  (let [id (new-id "sbot_tra")
        e {:db/id id
           :semicon_robotics.TransferJob/id id
           :semicon_robotics.TransferJob/robotId (get data :robotId)
           :semicon_robotics.TransferJob/source (get data :source)
           :semicon_robotics.TransferJob/destination (get data :destination)
           :semicon_robotics.TransferJob/status (get data :status)
           :semicon_robotics.TransferJob/createdAt (now)
           :semicon_robotics.TransferJob/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-transfer-jobs
  "List TransferJob with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-transfer-jobs port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :semicon_robotics.TransferJob/id))
         rows (apply-filters rows (:filter opts) [:semicon_robotics.TransferJob/robotId :semicon_robotics.TransferJob/source :semicon_robotics.TransferJob/destination :semicon_robotics.TransferJob/status])]
     (paginate rows opts))))

(defn get-transfer-job
  "Retrieve a TransferJob by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-transfer-job port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-transfer-job
  "Update a TransferJob; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :robotId) (conj [:db/add id :semicon_robotics.TransferJob/robotId (get data :robotId)]))
                   (cond-> (contains? data :source) (conj [:db/add id :semicon_robotics.TransferJob/source (get data :source)]))
                   (cond-> (contains? data :destination) (conj [:db/add id :semicon_robotics.TransferJob/destination (get data :destination)]))
                   (cond-> (contains? data :status) (conj [:db/add id :semicon_robotics.TransferJob/status (get data :status)]))
                   (conj [:db/add id :semicon_robotics.TransferJob/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-transfer-job
  "Delete a TransferJob."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── LoadPort ────────────────────────────────────────────────────────────────
(defn create-load-port
  "Create a LoadPort."
  [port data]
  (require-fields data ["standard" "slots"])
  (let [id (new-id "sbot_loa")
        e {:db/id id
           :semicon_robotics.LoadPort/id id
           :semicon_robotics.LoadPort/moduleId (get data :moduleId)
           :semicon_robotics.LoadPort/standard (get data :standard)
           :semicon_robotics.LoadPort/slots (as-long (get data :slots))
           :semicon_robotics.LoadPort/occupied (as-bool (get data :occupied))
           :semicon_robotics.LoadPort/createdAt (now)
           :semicon_robotics.LoadPort/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-load-ports
  "List LoadPort with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-load-ports port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :semicon_robotics.LoadPort/id))
         rows (apply-filters rows (:filter opts) [:semicon_robotics.LoadPort/moduleId :semicon_robotics.LoadPort/standard :semicon_robotics.LoadPort/slots :semicon_robotics.LoadPort/occupied])]
     (paginate rows opts))))

(defn get-load-port
  "Retrieve a LoadPort by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-load-port port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-load-port
  "Update a LoadPort; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :moduleId) (conj [:db/add id :semicon_robotics.LoadPort/moduleId (get data :moduleId)]))
                   (cond-> (contains? data :standard) (conj [:db/add id :semicon_robotics.LoadPort/standard (get data :standard)]))
                   (cond-> (contains? data :slots) (conj [:db/add id :semicon_robotics.LoadPort/slots (as-long (get data :slots))]))
                   (cond-> (contains? data :occupied) (conj [:db/add id :semicon_robotics.LoadPort/occupied (as-bool (get data :occupied))]))
                   (conj [:db/add id :semicon_robotics.LoadPort/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-load-port
  "Delete a LoadPort."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── MotionProgram ────────────────────────────────────────────────────────────────
(defn create-motion-program
  "Create a MotionProgram."
  [port data]
  (require-fields data ["name" "waypoints"])
  (let [id (new-id "sbot_mot")
        e {:db/id id
           :semicon_robotics.MotionProgram/id id
           :semicon_robotics.MotionProgram/robotId (get data :robotId)
           :semicon_robotics.MotionProgram/name (get data :name)
           :semicon_robotics.MotionProgram/waypoints (as-long (get data :waypoints))
           :semicon_robotics.MotionProgram/cycleTimeS (as-double (get data :cycleTimeS))
           :semicon_robotics.MotionProgram/createdAt (now)
           :semicon_robotics.MotionProgram/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-motion-programs
  "List MotionProgram with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-motion-programs port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :semicon_robotics.MotionProgram/id))
         rows (apply-filters rows (:filter opts) [:semicon_robotics.MotionProgram/robotId :semicon_robotics.MotionProgram/name :semicon_robotics.MotionProgram/waypoints :semicon_robotics.MotionProgram/cycleTimeS])]
     (paginate rows opts))))

(defn get-motion-program
  "Retrieve a MotionProgram by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-motion-program port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-motion-program
  "Update a MotionProgram; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :robotId) (conj [:db/add id :semicon_robotics.MotionProgram/robotId (get data :robotId)]))
                   (cond-> (contains? data :name) (conj [:db/add id :semicon_robotics.MotionProgram/name (get data :name)]))
                   (cond-> (contains? data :waypoints) (conj [:db/add id :semicon_robotics.MotionProgram/waypoints (as-long (get data :waypoints))]))
                   (cond-> (contains? data :cycleTimeS) (conj [:db/add id :semicon_robotics.MotionProgram/cycleTimeS (as-double (get data :cycleTimeS))]))
                   (conj [:db/add id :semicon_robotics.MotionProgram/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-motion-program
  "Delete a MotionProgram."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Interlock ────────────────────────────────────────────────────────────────
(defn create-interlock
  "Create a Interlock."
  [port data]
  (require-fields data ["kind" "triggered"])
  (let [id (new-id "sbot_int")
        e {:db/id id
           :semicon_robotics.Interlock/id id
           :semicon_robotics.Interlock/robotId (get data :robotId)
           :semicon_robotics.Interlock/kind (get data :kind)
           :semicon_robotics.Interlock/triggered (as-bool (get data :triggered))
           :semicon_robotics.Interlock/severity (get data :severity)
           :semicon_robotics.Interlock/createdAt (now)
           :semicon_robotics.Interlock/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-interlocks
  "List Interlock with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-interlocks port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :semicon_robotics.Interlock/id))
         rows (apply-filters rows (:filter opts) [:semicon_robotics.Interlock/robotId :semicon_robotics.Interlock/kind :semicon_robotics.Interlock/triggered :semicon_robotics.Interlock/severity])]
     (paginate rows opts))))

(defn get-interlock
  "Retrieve a Interlock by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-interlock port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-interlock
  "Update a Interlock; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :robotId) (conj [:db/add id :semicon_robotics.Interlock/robotId (get data :robotId)]))
                   (cond-> (contains? data :kind) (conj [:db/add id :semicon_robotics.Interlock/kind (get data :kind)]))
                   (cond-> (contains? data :triggered) (conj [:db/add id :semicon_robotics.Interlock/triggered (as-bool (get data :triggered))]))
                   (cond-> (contains? data :severity) (conj [:db/add id :semicon_robotics.Interlock/severity (get data :severity)]))
                   (conj [:db/add id :semicon_robotics.Interlock/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-interlock
  "Delete a Interlock."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── REST surface (host wires these to the kotoba-clj gateway) ──────────────
(def routes
  [{:method "POST" :path "/v1/waferrobots" :op :create :entity "WaferRobot"}
   {:method "GET" :path "/v1/waferrobots" :op :list :entity "WaferRobot"}
   {:method "GET" :path "/v1/waferrobots/:id" :op :get :entity "WaferRobot"}
   {:method "PATCH" :path "/v1/waferrobots/:id" :op :update :entity "WaferRobot"}
   {:method "DELETE" :path "/v1/waferrobots/:id" :op :delete :entity "WaferRobot"}
   {:method "POST" :path "/v1/efemmodules" :op :create :entity "EfemModule"}
   {:method "GET" :path "/v1/efemmodules" :op :list :entity "EfemModule"}
   {:method "GET" :path "/v1/efemmodules/:id" :op :get :entity "EfemModule"}
   {:method "PATCH" :path "/v1/efemmodules/:id" :op :update :entity "EfemModule"}
   {:method "DELETE" :path "/v1/efemmodules/:id" :op :delete :entity "EfemModule"}
   {:method "POST" :path "/v1/transferjobs" :op :create :entity "TransferJob"}
   {:method "GET" :path "/v1/transferjobs" :op :list :entity "TransferJob"}
   {:method "GET" :path "/v1/transferjobs/:id" :op :get :entity "TransferJob"}
   {:method "PATCH" :path "/v1/transferjobs/:id" :op :update :entity "TransferJob"}
   {:method "DELETE" :path "/v1/transferjobs/:id" :op :delete :entity "TransferJob"}
   {:method "POST" :path "/v1/loadports" :op :create :entity "LoadPort"}
   {:method "GET" :path "/v1/loadports" :op :list :entity "LoadPort"}
   {:method "GET" :path "/v1/loadports/:id" :op :get :entity "LoadPort"}
   {:method "PATCH" :path "/v1/loadports/:id" :op :update :entity "LoadPort"}
   {:method "DELETE" :path "/v1/loadports/:id" :op :delete :entity "LoadPort"}
   {:method "POST" :path "/v1/motionprograms" :op :create :entity "MotionProgram"}
   {:method "GET" :path "/v1/motionprograms" :op :list :entity "MotionProgram"}
   {:method "GET" :path "/v1/motionprograms/:id" :op :get :entity "MotionProgram"}
   {:method "PATCH" :path "/v1/motionprograms/:id" :op :update :entity "MotionProgram"}
   {:method "DELETE" :path "/v1/motionprograms/:id" :op :delete :entity "MotionProgram"}
   {:method "POST" :path "/v1/interlocks" :op :create :entity "Interlock"}
   {:method "GET" :path "/v1/interlocks" :op :list :entity "Interlock"}
   {:method "GET" :path "/v1/interlocks/:id" :op :get :entity "Interlock"}
   {:method "PATCH" :path "/v1/interlocks/:id" :op :update :entity "Interlock"}
   {:method "DELETE" :path "/v1/interlocks/:id" :op :delete :entity "Interlock"}])

;; collection → CRUD fns, keyed by the /v1/<collection> path segment
(def ^:private handlers
  {"waferrobots" {:create create-wafer-robot :list list-wafer-robots :get get-wafer-robot :update update-wafer-robot :delete delete-wafer-robot}
   "efemmodules" {:create create-efem-module :list list-efem-modules :get get-efem-module :update update-efem-module :delete delete-efem-module}
   "transferjobs" {:create create-transfer-job :list list-transfer-jobs :get get-transfer-job :update update-transfer-job :delete delete-transfer-job}
   "loadports" {:create create-load-port :list list-load-ports :get get-load-port :update update-load-port :delete delete-load-port}
   "motionprograms" {:create create-motion-program :list list-motion-programs :get get-motion-program :update update-motion-program :delete delete-motion-program}
   "interlocks" {:create create-interlock :list list-interlocks :get get-interlock :update update-interlock :delete delete-interlock}})

(defn- expand-opts [params]
  (when-let [x (:expand params)]
    {:expand (set (map keyword (str/split (str x) #",")))}))

(defn dispatch
  "Route an HTTP-ish request through `routes` to the CRUD fns.
   req: {:method (:get/:post/:patch/:delete) :path /v1/<coll>[/<id>] :params {} :body {}}.
   Returns {:status int :body any} — the runnable L4 service surface."
  [port {:keys [method path params body]}]
  (let [segs (->> (str/split (or path "") #"/") (remove str/blank?) vec)
        coll (get segs 1)
        id   (get segs 2)
        h    (get handlers coll)
        params (or params {})]
    (cond
      (nil? h) {:status 404 :body {:error "unknown collection"}}
      (and (= method :post) (nil? id)) {:status 201 :body ((:create h) port (or body params))}
      (and (= method :get) (nil? id)) {:status 200 :body ((:list h) port params)}
      (and (= method :get) id) (if-let [r ((:get h) port id (expand-opts params))]
                                 {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (#{:patch :put} method) id) (if-let [r ((:update h) port id (or body params))]
                                         {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (= method :delete) id) {:status 200 :body ((:delete h) port id)}
      :else {:status 405 :body {:error "method not allowed"}})))

(defn healthz []
  {:status "ok" :actor "semicon_robotics-compat" :tier "L4"
   :lang "clojure" :persistence "datomic-eavt-kotoba"
   :entities entities})
